export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GENERAL_ERROR = "GENERAL_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SUCCESS_STATUS = "SUCCESS_STATUS";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_USER_PREFERENCES = "SET_USER_PREFERENCES";
export const GET_USER_PREFERENCES = "SET_USER_PREFERENCES";
export const SEARCH_RECIPE = "SEARCH_RECIPE";
export const SAVE_RECIPE = "SAVE_RECIPE";
export const GET_SAVED_RECIPES = "GET_SAVED_RECIPES";
export const DELETE_SAVED_RECIPE = "DELETE_SAVED_RECIPE";
export const SET_NUTRITION_OBJECT = "SET_NUTRITION_OBJECT";
export const SET_HEALTH_LABELS = "SET_HEALTH_LABELS";

export const ADD_RECCOMENDED_RECIPE = "ADD_RECCOMENDED_RECIPE";
export const GET_RECCOMENDED_RECIPES = "GET_RECCOMENDED_RECIPES";

export const ADD_RECIPE_RATING = "ADD_RECIPE_RATING";
export const GET_RECIPE_RATINGS = "GET_RECIPE_RATINGS";

export const NEW_IMAGE_FILE = "NEW_IMAGE_FILE";
export const GET_IMAGE_FILES = "GET_IMAGE_FILES";

export const FILTER_RECOMMENDED_RECIPES = "FILTER_RECOMMENDED_RECIPE";
export const CLEAR_FILTERED_RECOMMENDED_RECIPES =
  "CLEAR_FILTERED_RECOMMENDED_RECIPES";

export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_MY_POSTS = "GET_MY_POSTS";

export const ADD_POST = "ADD_POST";

export const ADD_POST_REPLIES = "ADD_POST_REPLIES";
export const GET_POST_REPLIES = "GET_POST_REPLIES";
