export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GENERAL_ERROR = "GENERAL_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SUCCESS_STATUS = "SUCCESS_STATUS";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_USER_PREFERENCES = "SET_USER_PREFERENCES";
export const GET_USER_PREFERENCES = "SET_USER_PREFERENCES";
export const SEARCH_RECIPE = "SEARCH_RECIPE";
export const SAVE_RECIPE = "SAVE_RECIPE";
export const GET_SAVED_RECIPES = "GET_SAVED_RECIPES";
export const DELETE_SAVED_RECIPE = "DELETE_SAVED_RECIPE";
export const SET_NUTRITION_OBJECT = "SET_NUTRITION_OBJECT";
export const SET_HEALTH_LABELS = "SET_HEALTH_LABELS";

export const ADD_RECCOMENDED_RECIPE = "ADD_RECCOMENDED_RECIPE";
export const GET_RECCOMENDED_RECIPES = "GET_RECCOMENDED_RECIPES";

export const ADD_RECIPE_RATING = "ADD_RECIPE_RATING";
export const GET_RECIPE_RATINGS = "GET_RECIPE_RATINGS";
